SMS Motion sensor noise parameters as constants
4Subsea/smsfusion-python pull request #77
Opened 2024-11-22 10:59 UTC by vegard-solum-4ss

### This PR is related to user story DLAB-

## Description
Provide a short description about the work that has been done.

## Checklist
- [ ] PR title is descriptive and fit for injection into release notes (see tips below).
- [ ] Correct label(s) are used.

PR title tips:
* Use imperative mood.
* Describe the motivation for change, issue that has been solved or what has been improved - not how.
* Examples:
  * Add functionality for Allan variance to smsfusion.simulate
  * Upgrade to support Python 3.10
  * Remove MacOS from CI

2024-11-22 11:18 UTC, vegard-solum-4ss commented
Waiting for reply from Per regarding the noise parameter values we should use.

2024-11-25 14:00 UTC, ali-cetin-4ss requested changes

2024-11-25 14:00 UTC, ali-cetin-4ss commented on src/smsfusion/constants/_constants.py
> +}
```suggestion
ERR_ACC_MOTION1 = {
    "N": 0.004,
    "B": 0.0007,
    "tau_cb": 50.0,
}

ERR_GYRO_MOTION1 = {
    "N": 0.00009,
    "B": 0.00003,
    "tau_cb": 50.0,
}

ERR_ACC_MOTION2 = {
    "N": 0.0007,
    "B": 0.0005,
    "tau_cb": 50.0,
}

ERR_GYRO_MOTION2 = {
    "N": 0.00005,
    "B": 0.00003,
    "tau_cb": 50.0,
}
```

2024-11-25 14:31 UTC, ali-cetin-4ss approved these changes

2024-11-25 14:32 UTC, merged